apiVersion: v1
kind: Secret
metadata:
  name: config
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "gitlint-bot.labels" . | nindent 4 }}
type: Opaque
data:
  APP_ID: {{ .Values.secrets.APP_ID | b64enc }}
  DB_URL: {{ .Values.secrets.DB_URL | b64enc }}
  PRIVATE_KEY: {{ .Values.secrets.PRIVATE_KEY | b64enc }}
  WEBHOOK_SECRET: {{ .Values.secrets.WEBHOOK_SECRET | b64enc }}
  SLACK_WEBHOOK_URL: {{ .Values.secrets.SLACK_WEBHOOK_URL | b64enc }}
  SENTRY_DSN:  {{ .Values.secrets.SENTRY_DSN | default "" | b64enc }}