apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.appName }}"
    version: "{{ .Values.appVersion }}"
  name: "{{ .Values.appName }}"
  namespace: "{{ .Values.namespace }}"
spec:
  type: { { .Values.service.type } }
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: "{{ .Values.appName }}"
