apiVersion: batch/v1
kind: Job
metadata:
  name: gitlint-bot-db-migrations
spec:
  template:
    spec:
      containers:
        - name: gitlint-bot-db-migrations
          image: gcr.io/oursky-kube/gitlint-bot:latest
          command: ["npm", "run", "migrations"]
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: config
                  key: DB_URL
      restartPolicy: OnFailure
