name: gitlint-bot CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Check code formatting
        run: npm run check-format
      - name: Lint TypeScript
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Build TypeScript
        run: npm run build
